[versions]
groovy        = "4.0.5"
javafx        = "19"
ikonli        = "12.3.1"
junit         = "5.8.2"
javacpp       = "1.5.7"
opencv        = "4.5.5-1.5.7"
cuda          = "11.6-8.3-1.5.7"
bioformats    = "6.11.0"

[libraries]
groovy-core   = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-jsr223 = { module = "org.apache.groovy:groovy-jsr223", version.ref = "groovy" }
groovy-xml    = { module = "org.apache.groovy:groovy-xml", version.ref = "groovy" }

gson          = { module = "com.google.code.gson:gson", version = "2.9.1" }

# Optionally add GeoJSON support (brings in json-simple as sub-dependency)
#Â However, the use of simple-json is troublesome since it brings in an old version of junit
jts           = { module = "org.locationtech.jts:jts-core",    version = "1.19.0" }

logback       = { module = "ch.qos.logback:logback-classic",   version = "1.3.1" }
slf4j         = { module = "org.slf4j:slf4j-api",              version = "2.0.1" }

commons-math  = { module = "org.apache.commons:commons-math3", version = "3.6.1" }
commons-text  = { module = "org.apache.commons:commons-text",  version = "1.9" }
controlsfx    = { module = "org.controlsfx:controlsfx",        version = "11.1.1" }
jfxtras       = { module = "org.jfxtras:jfxtras-menu",         version = "11-r2" }
guava         = { module = "com.google.guava:guava",           version = "31.1-jre" }
imagej        = { module = "net.imagej:ij",                    version = "1.53t" }
picocli       = { module = "info.picocli:picocli",             version = "4.6.3" }

richtextfx    = { module = "org.fxmisc.richtext:richtextfx",   version = "0.10.9" }
jfreesvg      = { module = "org.jfree:org.jfree.svg",          version = "5.0.3" }

javacpp       = { module = "org.bytedeco:javacpp",              version.ref = "javacpp" }
opencv        = { module = "org.bytedeco:opencv-platform",      version.ref = "opencv" }
opencv-gpu    = { module = "org.bytedeco:opencv-platform-gpu",  version.ref = "opencv"}
cuda          = { module = "org.bytedeco:cuda-platform",        version.ref = "cuda" }
cuda-redist   = { module = "org.bytedeco:cuda-platform-redist", version.ref = "cuda" }

ikonli-javafx    = { module = "org.kordamp.ikonli:ikonli-javafx",  version.ref = "ikonli" }
ikonli-ionicons4 = { module = "org.kordamp.ikonli:ikonli-ionicons4-pack", version.ref = "ikonli" }

junit         = { module = "org.junit.jupiter:junit-jupiter",        version.ref = "junit" }
junit-api     = { module = "org.junit.jupiter:junit-jupiter-api",    version.ref = "junit" }
junit-engine  = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

commonmark    = { module = "org.commonmark:commonmark", version = "0.19.0" }

snakeyaml     = { module = "org.yaml:snakeyaml", version = "1.33" }

[bundles]
groovy        = ["groovy-core", "groovy-jsr223", "groovy-xml"]
ikonli        = ["ikonli-javafx", "ikonli-ionicons4"]
logging       = ["slf4j", "logback"]
opencv        = ["javacpp", "opencv"]
opencv-gpu    = ["javacpp", "opencv-gpu", "cuda"]
opencv-cuda   = ["javacpp", "opencv-gpu", "cuda", "cuda-redist"]
markdown      = ["commonmark"]

[plugins]
# Use the javafx plugin to add modules
javafx         = { id = 'org.openjfx.javafxplugin', version = '0.0.12' }
javacpp        = { id = 'org.bytedeco.gradle-javacpp-platform', version = '1.5.7' }
jpackage       = { id = 'org.beryx.runtime', version = '1.12.7' }
license-report = { id = 'com.github.jk1.dependency-license-report', version = '2.0' }
